"use strict";

const { Customer, Role, RoleTag } = require("../models");
const { v4: uuidv4 } = require("uuid");

module.exports = async () => {
  const now = new Date();

  const customerRoleTag = await RoleTag.findOne({
    where: { name: "customer" },
  });
  const customerRole = await Role.findOne({ where: { name: "Customer" } });

  if (!customerRoleTag || !customerRole) {
    throw new Error(
      "Customer role or role_tag not found. Please seed roles first."
    );
  }

  const customerData = [
    {
      id: uuidv4(),
      first_name: "Nati",
      last_name: "Keleme",
      email: "nathnaelkeleme88@gmail.com",
      password: "12345678",
      profile_picture:
        "https://static.vecteezy.com/system/resources/previews/002/002/403/non_2x/man-with-beard-avatar-character-isolated-icon-free-vector.jpg",
      dob: new Date(1990, 0, 1),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Sif",
      last_name: "Mekonnen",
      email: "sifen1995mek@gmail.com",
      password: "12345678",
      profile_picture:
        "https://img.freepik.com/premium-vector/avatar-profile-icon-flat-style-female-user-profile-vector-illustration-isolated-background-women-profile-sign-business-concept_157943-38866.jpg",
      dob: new Date(1991, 1, 2),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Michael",
      last_name: "Johnson",
      email: "michaeljohnson@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/3.jpg",
      dob: new Date(1992, 2, 3),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Emily",
      last_name: "Williams",
      email: "emilywilliams@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/4.jpg",
      dob: new Date(1993, 3, 4),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "David",
      last_name: "Brown",
      email: "davidbrown@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/5.jpg",
      dob: new Date(1994, 4, 5),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Sarah",
      last_name: "Jones",
      email: "sarahjones@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/6.jpg",
      dob: new Date(1995, 5, 6),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Robert",
      last_name: "Garcia",
      email: "robertgarcia@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/7.jpg",
      dob: new Date(1996, 6, 7),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Jennifer",
      last_name: "Martinez",
      email: "jennifermartinez@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/8.jpg",
      dob: new Date(1997, 7, 8),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Thomas",
      last_name: "Wilson",
      email: "thomaswilson@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/9.jpg",
      dob: new Date(1998, 8, 9),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Lisa",
      last_name: "Anderson",
      email: "lisaanderson@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/10.jpg",
      dob: new Date(1999, 9, 10),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Daniel",
      last_name: "Clark",
      email: "danielclark@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/11.jpg",
      dob: new Date(1990, 10, 11),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Olivia",
      last_name: "Lewis",
      email: "olivialewis@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/12.jpg",
      dob: new Date(1991, 11, 12),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Matthew",
      last_name: "Hall",
      email: "matthewhall@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/13.jpg",
      dob: new Date(1992, 1, 13),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "Sophia",
      last_name: "Allen",
      email: "sophiaallen@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/women/14.jpg",
      dob: new Date(1993, 2, 14),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      first_name: "James",
      last_name: "Young",
      email: "jamesyoung@gmail.com",
      password: "12345678",
      profile_picture: "https://randomuser.me/api/portraits/men/15.jpg",
      dob: new Date(1994, 3, 15),
      email_verified_at: now,
      role_id: customerRole.id,
      role_tag_id: customerRoleTag.id,
      created_at: now,
      updated_at: now,
    },
  ];

  await Customer.bulkCreate(customerData);
  console.log("✅ 15 Customers seeded successfully");
};
